name: Build

on: [ push, pull_request ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - run: mvn verify -B -e

  deploy:
    needs: verify
    runs-on: ubuntu-latest
    if: contains(github.ref, 'main')
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      # based on this : https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#yaml-example
      - name: setup maven
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          server-id: ossrh
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD

      - name: publish to snapshot
        run: mvn clean deploy -B -e
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}